### ISSUE TITLE
无法将爬取的数据保存到/root/DarkAngel/vulscan/results/urls

### ISSUE THREAD

**Issue by LonelyBoy2005** [Bywalks/DarkAngel#13]
[root@localhost DarkAngel]# python3 darkangel.py --add-new-domain

    ____             __   ___                     __
   / __ \____ ______/ /__/   |  ____  ____ ____  / /
  / / / / __ `/ ___/ //_/ /| | / __ \/ __ `/ _ \/ / 
 / /_/ / /_/ / /  / ,< / ___ |/ / / / /_/ /  __/ /  
/_____/\__,_/_/  /_/|_/_/  |_/_/ /_/\__, /\___/_/   
                                   /____/                  
                           By Bywalks | V 0.0.7    

DarkAngel is a white hat scanner. Every white hat makes the Internet more secure.        

02:27:26,108 [INFOR] darkangel:388 - [begin_time]2023-02-24 02:27:26.108900
02:27:56,145 [INFOR] collecth1domain:78 - Start collecting h1 private programs
02:27:57,103 [INFOR] collecth1domain:112 - 0 private programs have been Collected
02:27:57,104 [INFOR] collecth1domain:209 - Start collecting h1 new domains
02:27:57,664 [INFOR] ESHelper:79 - query dsl:{'query': {'match_all': {}}}, total:4968, res_cou
nt:4968
02:27:57,669 [INFOR] collecth1domain:249 - Finished
02:27:57,670 [INFOR] collecth1domain:38 - Start collecting h1 programs
02:29:05,132 [INFOR] collecth1domain:73 - 359 programs have been Collected
02:29:05,132 [INFOR] collecth1domain:166 - Start collecting h1 new domains
02:29:05,804 [INFOR] ESHelper:79 - query dsl:{'query': {'match_all': {}}}, total:4968, res_count:4968
02:37:31,971 [INFOR] collecth1domain:206 - Finished
02:37:31,971 [INFOR] collectbcdomain:54 - Start collecting bc programs
02:37:32,808 [INFOR] ESHelper:79 - query dsl:{'query': {'match_all': {}}}, total:4968, res_count:4968
02:37:32,813 [INFOR] collectbcdomain:64 - https://bugcrowd.com/programs.json?sort[]=promoted-desc&hidden[]=false&page[]=1
02:37:34,677 [INFOR] collectbcdomain:70 - [+] Collecting... (24 programs)
02:37:44,034 [INFOR] collectbcdomain:130 - [+] Program empty-sea-5360 returned a status code 404, skipping program details...
02:38:01,975 [INFOR] collectbcdomain:130 - [+] Program twilight-moon-8601 returned a status code 404, skipping program details...
02:38:03,022 [INFOR] collectbcdomain:130 - [+] Program D28qs1YDrtgsf5fFDf4asFLX returned a status code 404, skipping program details...
我问题好多...作者理解下，小白一枚

**Comment by LonelyBoy2005** [comment]
/root/DarkAngel/vulscan/results/urls该路劲下的txt文本全没有数据

**Comment by Bywalks** [comment]
程序正常运行....结果会实时打到kibana，全部扫完会给urls文件夹两个url文件

**Comment by daxin09pp** [comment]
我也是运行完了URLs里面没有内容。
