### ISSUE TITLE
运行es报错

### ISSUE THREAD

**Issue by Ershu1** [Bywalks/DarkAngel#14]
运行python3 darkangel.py --add-domain-and-scan命令的时候，ES报错如下

`
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fba2283d390>: Failed to establish a new connection: [Errno -2] Name or service not known) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fba2283d390>: Failed to establish a new connection: [Errno -2] Name or service not known)
`
请问是哪里出错了吗？

**Comment by Ershu1** [comment]
```
部署Kibana镜像（修改一下es-ip）
docker run --name kibana -e ELASTICSEARCH_URL=http://es-ip:9200 -p 5601:5601 -d docker.io/bywalkss/darkangel:kibana7.9.3
```

es-ip 是服务器IP？

**Comment by Ershu1** [comment]
已解决

**Comment by Bywalks** [comment]
es-ip 是服务器IP

**Comment by Ershu1** [comment]
> es-ip 是服务器IP

ES未连接的报错还需要在哪里修改配置文件？

**Comment by Bywalks** [comment]
报错说明你设置的不对。可拉取下新的代码，昨天做了更新，设置错误运行时会有提示

**Comment by Ershu1** [comment]
> 报错说明你设置的不对。可拉取下新的代码，昨天做了更新，设置错误运行时会有提示

ok ，我试下，感谢

**Comment by Bywalks** [comment]
自添加域名的情况下，配置es-ip就可以使用，你浏览器访问一下你修改后的http://es-ip:9200。

提示：ES未连接，请检查配置文件是否填写或是否正确。

很明显你的ES就没配置好，浏览器应该也访问不了。
