### ISSUE TITLE
git clone-fatal: Could not get current working directory: No such file or directory

### ISSUE THREAD

**Issue by skypoc** [Bywalks/DarkAngel#18]
Hi, thank you very much for developing such an excellent tool.
But there were some problems during my installation
**Scanner image:**
```
Download source code
git clone https://github.com/Bywalks/DarkAngel.git
```
system always reports an error---fatal: Could not get current working directory: No such file or directory
I have already run setenforce 0 on the host 

I would be grateful if you could reply!😊

**Comment by Bywalks** [comment]
It seems like the network from your computer to github is blocked.

**Comment by skypoc** [comment]
Thank you for your reply! 
I'll use a proxy and try again
