### ISSUE TITLE
xray扫描卡顿，还有企业微信配置没有消息通知，请问怎么配置有漏洞通知呢

### ISSUE THREAD

**Issue by small-zero** [Bywalks/DarkAngel#19]

**Comment by small-zero** [comment]
xray扫描卡顿，还有企业微信配置没有消息通知，请问怎么配置有漏洞通知呢 #19

**Comment by Bywalks** [comment]
1：xray扫描卡顿
我暂时没遇到，可以给log日志给我

2：企业微信配置没有消息通知
企业微信配置没有消息通知说明配置错误，搜搜教程
