### ISSUE TITLE
扫描完毕后

### ISSUE THREAD

**Issue by daxin09pp** [Bywalks/DarkAngel#21]
使用python3 darkangel.py --add-new-domain后扫描完毕后没有报错，数据进入了Kibana，但是没有url生成在/root/DarkAngel/vulscan/results/urls/里面。
![image](https://github.com/Bywalks/DarkAngel/assets/12574090/0efbc903-be4e-4078-9e95-71d33517ee4c)
![image](https://github.com/Bywalks/DarkAngel/assets/12574090/f4278ba9-6990-46bc-a349-4fc786b1ce79)

然后使用 python3 darkangel.py --nuclei-file-scan扫描，因为/root/DarkAngel/vulscan/results/urls/里面没有数据，所以扫描不出结果。

这几个命令的先后顺序是什么样子的呀？

**Comment by Bywalks** [comment]
--add-new-domain参数仅添加域名到kibana，如果是泛域名的话需要进行子域名扫描，可以拿--scan-domain-by-time参数进行扫描（包含子域名、漏洞扫描等动作），扫描完成后会把扫描出来的子域名输出到/root/DarkAngel/vulscan/results/urls/，如上的两个动作等同于--add-domain-and-scan

这块输出的url文件并不会在20个序号的txt文件中，需要自行复制粘贴到这20个文件中

**Comment by daxin09pp** [comment]
谢谢
