### ISSUE TITLE
es启动失败

### ISSUE THREAD

**Issue by brucelsone** [Bywalks/DarkAngel#22]
拉取镜像之后启动出错，扩充了内存还是启动不了，镜像直接关闭了
<img width="1060" alt="image" src="https://github.com/Bywalks/DarkAngel/assets/101378596/0f8336a6-d606-4a82-9d16-598a75a73685">
查看日志报错：
<img width="1049" alt="image" src="https://github.com/Bywalks/DarkAngel/assets/101378596/1882132a-e9a2-4af3-9977-8c32e7a5e61e">

**Comment by Bywalks** [comment]
报错已经有说明，百度下就能解决。
