### ISSUE TITLE
docker logs -f elasticsearch 一堆报错，可以直接拉取Kibana和 Elasticsearch官网镜像吗

### ISSUE THREAD

**Issue by maye-gitch** [Bywalks/DarkAngel#4]
![image](https://user-images.githubusercontent.com/74856276/209345179-69a0cf49-de38-4698-8e3a-90ee2fac5f4e.png)

**Comment by Bywalks** [comment]
处理方式在我的安装过程中有给

出现问题，执行命令
sysctl -w vm.max_map_count=262144

**Comment by Bywalks** [comment]
很久未回复，关闭这个issue
