### ISSUE TITLE
sh: /root/darkangel/vulscan/tools/nuclei: Permission denied

### ISSUE THREAD

**Issue by locky504** [Bywalks/DarkAngel#6]
为什么会提示没有权限，这问题一直让扫描无法进行下去
<img width="1157" alt="bug3" src="https://user-images.githubusercontent.com/49021928/209655158-4e6ebcba-9a6a-4f4a-a460-9c75283070e7.png">

**Comment by Bywalks** [comment]
chmod 777 /root/darkangel/vulscan/tools/*

**Comment by locky504** [comment]
Could not create runner: could not create output file: could not create output file: open /root/darkangel/vulscan/results/nuclei/bc_no_bounty_04_nuclei_output.json: no such file or directory，那这种这种一堆红色报错怎么解决？
<img width="1156" alt="bug4" src="https://user-images.githubusercontent.com/49021928/209746939-c5c9ac10-30df-49bc-aff3-55e73ac1fb34.png">

**Comment by Bywalks** [comment]
已更新

重新拉取一下新版本镜像 docker push bywalkss/darkangel:v0.0.2

或者更新一下源代码git clone https://github.com/Bywalks/DarkAngel.git

**Comment by locky504** [comment]
我重新拉了v0.0.2，现在已经停止运行了，没有进行扫描，看不到扫描记录

**Comment by Bywalks** [comment]
没理解你的意思，有异常贴异常图片

**Comment by locky504** [comment]
![bug5](https://user-images.githubusercontent.com/49021928/210031671-028d5093-9763-4bf9-b2e9-745ece06b31f.jpg)
<img width="434" alt="bug6" src="https://user-images.githubusercontent.com/49021928/210031858-db33e423-0638-45c2-9233-31d0375e9e5a.png">
这样子能理解吗？只有扫描开始的提示，没有扫描结束的提示，然后我看了docker的进程，程序已经结束运行了

**Comment by Bywalks** [comment]
我的执行过程是正常的，我刚更新了一下代码，你重新git拉取一下，再有异常的话把/root/darkangel/vulscan/results/log/路径下的log给我。

**Comment by Bywalks** [comment]
docker执行程序可以嵌入一个screen，这样有异常直接可以进入screen里面看。

**Comment by Bywalks** [comment]
v0.0.2的镜像加入了screen。

**Comment by locky504** [comment]
> 我的执行过程是正常的，我刚更新了一下代码，你重新git拉取一下，再有异常的话把/root/darkangel/vulscan/results/log/路径下的log给我。

没有日志，目录是空的。我已经重试了好多次了，这个版本真的蛮多使用问题，你看其他人提出的问题就知道了，并不只有我使用出现问题。

**Comment by Bywalks** [comment]
我完完全全的重新拉取了一遍，不存在问题，存在日志，你先确定一下你的代码更新了么，并不是拉取docker代码就会更新，还需复制下源代码  cp -r /root/DarkAngel/* /root/darkangel/

![image](https://user-images.githubusercontent.com/32921125/210052770-368fd08c-3f30-4258-8078-9c4daac46066.png)

**Comment by locky504** [comment]
> 我完完全全的重新拉取了一遍，不存在问题，存在日志，你先确定一下你的代码更新了么，并不是拉取docker代码就会更新，还需复制下源代码 cp -r /root/DarkAngel/* /root/darkangel/
> 
> ![image](https://user-images.githubusercontent.com/32921125/210052770-368fd08c-3f30-4258-8078-9c4daac46066.png)

这次有日志了，我再尝试一次，还是不行的话给你看日志，另外这程序没有优化内存占用，我16g内存运行两天都快感觉内存不够用了

**Comment by locky504** [comment]
https://tmp.link/f/63b1007908bb5
日志我导出来了，最新版本程序也不进行扫描，程序异常中止运行了

**Comment by Bywalks** [comment]
2023-01-01 02:06:18,339 [INFO ] darkangel.scan_module:144 - [Subdomain] 开始扫描第3753/4781-adobe-*.marketo.com

程序扫描过半，在oneforall扫描marketo.com子域名的时候出现了异常，该程序的扫描模块集成了很多工具，目前一次性扫描5K-10K个域名的情况下确实容易出现异常。等个周末我更新一版，进行部分程序部分程序的扫描。

**Comment by locky504** [comment]
> 2023-01-01 02:06:18,339 [INFO ] darkangel.scan_module:144 - [Subdomain] 开始扫描第3753/4781-adobe-*.marketo.com
> 
> 程序扫描过半，在oneforall扫描marketo.com子域名的时候出现了异常，该程序的扫描模块集成了很多工具，目前一次性扫描5K-10K个域名的情况下确实容易出现异常。等个周末我更新一版，进行部分程序部分程序的扫描。

内存优化有计划吗？运行两天，内存占用已经飙到十几G了

**Comment by Bywalks** [comment]
> > 2023-01-01 02:06:18,339 [INFO ] darkangel.scan_module:144 - [Subdomain] 开始扫描第3753/4781-adobe-*.marketo.com
> > 程序扫描过半，在oneforall扫描marketo.com子域名的时候出现了异常，该程序的扫描模块集成了很多工具，目前一次性扫描5K-10K个域名的情况下确实容易出现异常。等个周末我更新一版，进行部分程序部分程序的扫描。
> 
> 内存优化有计划吗？运行两天，内存占用已经飙到十几G了

这部分考虑一下，内存飙升是因为扫的父域名太多了，当第一次添加之后，之后每次加的域名大概就是十个左右，就不会有你出现的问题。

**Comment by Bywalks** [comment]
感谢频繁提交BUG，已把你加入项目感谢页面。

https://github.com/Bywalks/DarkAngel/blob/main/THANKS.md

**Comment by locky504** [comment]
大佬最近没更新吗？

**Comment by Bywalks** [comment]
已增加以时间间隔为条件，对es库中pdomain进行漏洞扫描模块

更新代码后看下如何使用
https://github.com/Bywalks/DarkAngel#--scan-domain-by-time
