### ISSUE TITLE
elasticsearch 启动报错

### ISSUE THREAD

**Issue by aiwennba** [Bywalks/DarkAngel#7]
![image](https://user-images.githubusercontent.com/8187904/209748541-3f0707e1-1566-48b7-9de3-9aea5719dfbb.png)
{"type": "server", "timestamp": "2022-12-28T02:36:05,187Z", "level": "INFO", "component": "o.e.b.BootstrapChecks", "cluster.name": "docker-cluster", "node.name": "b5bbe232d264", "message": "bound or publishing to a non-loopback address, enforcing bootstrap checks" }
ERROR: [1] bootstrap checks failed
[1]: the default discovery settings are unsuitable for production use; at least one of [discovery.seed_hosts, discovery.seed_providers, cluster.initial_master_nodes] must be configured
ERROR: Elasticsearch did not exit normally - check the logs at /usr/share/elasticsearch/logs/docker-cluster.log
{"type": "server", "timestamp": "2022-12-28T02:36:05,198Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "b5bbe232d264", "message": "stopping ..." }
{"type": "server", "timestamp": "2022-12-28T02:36:05,220Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "b5bbe232d264", "message": "stopped" }
{"type": "server", "timestamp": "2022-12-28T02:36:05,220Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "b5bbe232d264", "message": "closing ..." }
{"type": "server", "timestamp": "2022-12-28T02:36:05,233Z", "level": "INFO", "component": "o.e.n.Node", "cluster.name": "docker-cluster", "node.name": "b5bbe232d264", "message": "closed" }
{"type": "server", "timestamp": "2022-12-28T02:36:05,236Z", "level": "INFO", "component": "o.e.x.m.p.NativeController", "cluster.name": "docker-cluster", "node.name": "b5bbe232d264", "message": "Native controller process has stopped - no new native processes can be started" }

**Comment by Bywalks** [comment]
内存扩充了么

sysctl -w vm.max_map_count=262144

扩充了看下下面这篇文章

https://blog.csdn.net/qq_43655835/article/details/104637625

**Comment by aiwennba** [comment]
> 
内存扩充已经了

**Comment by Loppower** [comment]
启动命令改成这样试试
docker run -e ES_JAVA_OPTS="-Xms1024m -Xms1024m"  -e "discovery.type=single-node" -d -p 9200:9200 -p 9300:9300 --name elasticsearch elasticsearch:7.9.3

**Comment by Bywalks** [comment]
未看到提交人再回复，关闭该issue。
