### ISSUE TITLE
python3 darkangel.py --scan-domain-by-time 2023-1-18 2023-1-31，企业微信收不到扫描开始的推送

### ISSUE THREAD

**Issue by locky504** [Bywalks/DarkAngel#8]
能收到h1-token过期的推送，说明设置没问题

**Comment by Bywalks** [comment]
输入python3 darkangel.py --scan-domain-by-time 2023-1-18 2023-1-31后，从控制台直接可看到扫描是否开始，为什么还要推送到企业微信呢。

**Comment by locky504** [comment]
> 输入python3 darkangel.py --scan-domain-by-time 2023-1-18 2023-1-31后，从控制台直接可看到扫描是否开始，为什么还要推送到企业微信呢。

这个开始是可以看到，但是结束的时候不懂会不会推送扫描结束，总不能一直盯着docker那里看什么时候结束。开始和结束一般是成对的，都推送比较好。

**Comment by Bywalks** [comment]
> 

已更新，重新拉取下代码。
