### ISSUE TITLE
运行python darkangel.py报错

### ISSUE THREAD

**Issue by LonelyBoy2005** [Bywalks/DarkAngel#9]
└─# python darkangel.py

Traceback (most recent call last):
  File "/root/DarkAngel/darkangel.py", line 32, in <module>
    from vulscan.xray_scan import *
  File "/root/DarkAngel/vulscan/xray_scan.py", line 26, in <module>
    from vcommon.ESHelper import ESHelper
  File "/root/DarkAngel/vcommon/ESHelper.py", line 12, in <module>
    from elasticsearch import Elasticsearch, helpers
ModuleNotFoundError: No module named 'elasticsearch'

**Comment by LonelyBoy2005** [comment]
我所有镜像都搞好了，到这一步就出错

**Comment by Bywalks** [comment]
需要在扫描器docker镜像里面运行。

**Comment by LonelyBoy2005** [comment]
现在已经解决了，但是输入python3 darkangel.py --nuclei-file-scan后报错
，    ____             __   ___                     __                         
   / __ \____ ______/ /__/   |  ____  ____ ____  / /                         
  / / / / __ `/ ___/ //_/ /| | / __ \/ __ `/ _ \/ /                          
 / /_/ / /_/ / /  / ,< / ___ |/ / / / /_/ /  __/ /                           
/_____/\__,_/_/  /_/|_/_/  |_/_/ /_/\__, /\___/_/                            
                                   /____/                                    
                           By Bywalks | V 0.0.7                              
                                                                             
DarkAngel is a white hat scanner. Every white hat makes the Internet more secure.                                                                         
                                                                             
Traceback (most recent call last):                                           
  File "/root/DarkAngel/darkangel.py", line 981, in <module>                 
    main()                                                                   
  File "/root/DarkAngel/darkangel.py", line 948, in main                     
    darkAngel = DarkAngel()                                                  
  File "/root/DarkAngel/darkangel.py", line 81, in __init__                  
    self.xray_scan = XrayScan()                                              
NameError: name 'XrayScan' is not defined                                    
                                             请问怎么解决

**Comment by Bywalks** [comment]
https://github.com/Bywalks/DarkAngel#%E5%AE%89%E8%A3%85

照着说明去安装，运行就不存在问题了。
